#!/bin/bash
PORTS=$PWD/../wvports
./configure \
	--host=i586-mingw32msvc \
	--enable-exceptions \
	--with-xplc=$PORTS/xplc/build/xplc \
	CPPFLAGS="-mno-cygwin \
		-I$PORTS/xplc/build/xplc/include \
		-I$PORTS/zlib/build/zlib \
		-I$PORTS/openssl/build/openssl/include" \
	LDFLAGS="\
		-L$PORTS/xplc/build/xplc \
		-L$PORTS/zlib/build/zlib \
		-L$PORTS/openssl/build/openssl" \
	LIBS="-lxplc-cxx -lwsock32 -lgdi32" \
	$@
