#!/bin/bash
PORTS=$PWD/../../ports
./configure --host=i586-mingw32msvc \
	--enable-exceptions \
	--with-xplc=$PORTS/xplc/build/xplc \
	CPPFLAGS="\
		-I$PORTS/xplc/build/xplc/include \
		-I$PORTS/zlib/build/zlib \
		-I$PORTS/openssl/build/openssl/include" \
	LDFLAGS="\
		-L$PORTS/xplc/build/xplc \
		-L$PORTS/zlib/build/zlib \
		-L$PORTS/openssl/build/openssl" \
	LIBS="-lwsock32 -lgdi32" \
	$@
