#!/bin/sh +e
OUTFILE=$1
EXT=$2
TEMPDIR=`dirname \$EXT`
TEMPDEP=`dirname \$EXT`/.`basename \$EXT .o`.d
echo "* Generating $OUTFILE, using $2, $TEMPDIR and $TEMPDEP" >&2
TEMPFILE=gencc-$$.tmp

cat >$TEMPFILE <<-EOF 
	#!/bin/sh
	set -e
	
	MODE=\$1
	BASE=\$2
	DIR=$TEMPDIR
	DEPFILE=$TEMPDEP
	shift
	shift
	
	$CC \$MODE -o \$BASE.o \$BASE.$EXT \\
	        -MMD -MF \$DEPFILE -MP -MQ \$BASE.o \\
	        $CPPFLAGS \\
	        $CFLAGS \\
	        "\$@"
EOF

chmod a+x $TEMPFILE
mv $TEMPFILE $OUTFILE
