/* include/wvautoconf.h.  Generated by configure.  */
/* include/wvautoconf.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <crypt.h> header file. */
#define HAVE_CRYPT_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `crypt' library (-lcrypt). */
#define HAVE_LIBCRYPT 1

/* Define to 1 if you have the `fftw' library (-lfftw). */
#define HAVE_LIBFFTW 1

/* Define to 1 if you have the `ogg' library (-logg). */
#define HAVE_LIBOGG 1

/* Define to 1 if you have the `qt' library (-lqt). */
#define HAVE_LIBQT 1

/* Define to 1 if you have the `rfftw' library (-lrfftw). */
#define HAVE_LIBRFFTW 1

/* Define to 1 if you have the `speex' library (-lspeex). */
#define HAVE_LIBSPEEX 1

/* Define to 1 if you have the `ssl' library (-lssl). */
#define HAVE_LIBSSL 1

/* Define to 1 if you have the `vorbis' library (-lvorbis). */
#define HAVE_LIBVORBIS 1

/* Define to 1 if you have the `vorbisenc' library (-lvorbisenc). */
#define HAVE_LIBVORBISENC 1

/* Define to 1 if you have the `xplc' library (-lxplc). */
/* #undef HAVE_LIBXPLC */

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ogg/ogg.h> header file. */
#define HAVE_OGG_OGG_H 1

/* Define to 1 if you have the <openssl/ssl.h> header file. */
#define HAVE_OPENSSL_SSL_H 1

/* Define to 1 if you have the <qt/qobject.h> header file. */
#define HAVE_QT_QOBJECT_H 1

/* Define to 1 if you have the <rfftw.h> header file. */
#define HAVE_RFFTW_H 1

/* Define to 1 if you have the <speex.h> header file. */
#define HAVE_SPEEX_H 1

/* Define to 1 if you have the <speex_header.h> header file. */
#define HAVE_SPEEX_HEADER_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <vorbis/codec.h> header file. */
#define HAVE_VORBIS_CODEC_H 1

/* Define to 1 if you have the <vorbis/vorbisenc.h> header file. */
#define HAVE_VORBIS_VORBISENC_H 1

/* Define to 1 if you have the <xplc/core.h> header file. */
/* #undef HAVE_XPLC_CORE_H */

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "wvstreams-dev@nit.ca"

/* Define to the full name of this package. */
#define PACKAGE_NAME "wvstreams"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "wvstreams 3.71"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "wvstreams"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.71"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to disable WvResolver forking for debugging with gdb. */
/* #undef WVRESOLVER_SKIP_FORK */
